# Generated by Django 4.1.4 on 2023-01-23 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('S', 'Student'), ('E', 'Elder')], max_length=1)),
                ('birth_date', models.CharField(max_length=200)),
                ('remaining_hours', models.IntegerField(default=True)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(null=True, upload_to='images')),
            ],
            options={
                'db_table': 'base_users',
            },
        ),
    ]
