# Generated by Django 4.1.4 on 2023-01-28 12:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('S', 'Student'), ('E', 'Elder')], max_length=1)),
                ('birth_date', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(null=True, upload_to='images')),
                ('remaining_hours', models.IntegerField(default=250)),
            ],
            options={
                'db_table': 'base_users',
            },
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=200)),
                ('start_hour', models.CharField(choices=[('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00')], max_length=5)),
                ('time', models.CharField(choices=[('30 min', '30 min'), ('1 hour', '1 hour'), ('1.5 hour', '1.5 hour'), ('2 hours', '2 hours'), ('2.5 hours', '2.5 hours'), ('3 hours', '3 hours')], max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Registed', 'Registed'), ('Done', 'Done')], default='Pending', max_length=200)),
                ('creation_time', models.DateTimeField(default=datetime.datetime(2023, 1, 28, 12, 58, 41, 274359, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'base_chores',
            },
        ),
    ]
