# Generated by Django 4.1.4 on 2023-01-25 16:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('S', 'Student'), ('E', 'Elder')], max_length=1)),
                ('birth_date', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(null=True, upload_to='images')),
                ('remaining_hours', models.IntegerField(default=250)),
            ],
            options={
                'db_table': 'base_users',
            },
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('chore_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=200)),
                ('start_hour', models.CharField(choices=[('9', '09:00'), ('95', '09:30'), ('10', '10:0'), ('105', '10:30'), ('11', '11:00'), ('115', '11:30'), ('12', '12:00'), ('125', '12:30'), ('13', '13:00'), ('135', '13:30'), ('14', '14:00'), ('145', '14:30'), ('15', '15:00'), ('155', '15:30'), ('16', '16:00'), ('166', '16:30'), ('17', '17:00')], max_length=5)),
                ('time', models.CharField(choices=[('1', '30 min'), ('2', '1 hour'), ('3', '1.5 hour'), ('4', '2 hours'), ('5', '2.5 hours'), ('6', '3 hours')], max_length=200)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Registed'), ('D', 'Done')], default='P', max_length=200)),
                ('creation_time', models.DateTimeField(default=datetime.datetime(2023, 1, 25, 16, 11, 31, 447350, tzinfo=datetime.timezone.utc))),
                ('student_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'base_chores',
            },
        ),
    ]
