# Generated by Django 4.1.4 on 2023-01-25 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_chore_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 16, 19, 0, 424722, tzinfo=datetime.timezone.utc)),
        ),
    ]
